name: hero-showdown # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Hero Arena Showdown
summary: Battle heroes online in exciting matches.
description: Choose powerful heroes, master their abilities, and showcase your skills in dynamic multiplayer arenas.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  hero-showdown:
    command: bin/hero-showdown-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  hero-showdown:
    plugin: dump
    source: .
    organize:
      hero-showdown-bin: bin/
